//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDBTA.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cardapio
    {
        public cardapio()
        {
            this.item_cardapio = new HashSet<item_cardapio>();
        }
    
        public int idcardapio { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<item_cardapio> item_cardapio { get; set; }
    }
}
