//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDBTA.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumo_comanda
    {
        public int idconsumo_comanda { get; set; }
        public Nullable<int> idmesa { get; set; }
        public Nullable<int> idcomanda { get; set; }
        public Nullable<int> itemcardapio { get; set; }
        public Nullable<int> quantidade { get; set; }
    
        public virtual comanda comanda { get; set; }
        public virtual mesa mesa { get; set; }
    }
}
