//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDBTA.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesa
    {
        public mesa()
        {
            this.consumo_comanda = new HashSet<consumo_comanda>();
        }
    
        public int idmesa { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> vagas { get; set; }
    
        public virtual ICollection<consumo_comanda> consumo_comanda { get; set; }
    }
}
