//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDBTA.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public produto()
        {
            this.item_cardapio = new HashSet<item_cardapio>();
        }
    
        public int idproduto { get; set; }
        public string nome { get; set; }
        public Nullable<double> preco { get; set; }
        public Nullable<int> idtipo { get; set; }
    
        public virtual ICollection<item_cardapio> item_cardapio { get; set; }
        public virtual tipo tipo { get; set; }
    }
}
