//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDBTA.modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restaurantedbEntidades : DbContext
    {
        public restaurantedbEntidades()
            : base("name=restaurantedbEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cardapio> cardapio { get; set; }
        public DbSet<comanda> comanda { get; set; }
        public DbSet<consumo_comanda> consumo_comanda { get; set; }
        public DbSet<item_cardapio> item_cardapio { get; set; }
        public DbSet<mesa> mesa { get; set; }
        public DbSet<produto> produto { get; set; }
        public DbSet<tipo> tipo { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
